#ifndef PACKETIA_PROTOCOL_RTMP_PROTOCOL_H_
#define PACKETIA_PROTOCOL_RTMP_PROTOCOL_H_

#include <cstddef>
#include <cstdint>
#include <functional>
#include <vector>
#include "TcpSession.h"
#include "rtmp_chunck.h"

namespace protocol::rtmp {

enum class EndpointRole { kClient, kServer };
enum class ProtocolState { kHandshake, kChunkStream, kFailed };

class RtmpProtocol final : public itcp_sess::ICodec<RtmpMessage>
{
public:
    explicit RtmpProtocol(EndpointRole role);

    /* Feed raw TCP data and decode complete RTMP messages. */
    void Feed(const uint8_t* data, std::size_t size, std::vector<RtmpMessage>& messages) override;

    /* Encode an RTMP message into chunked wire data. */
    void Encode(const RtmpMessage& message, std::vector<uint8_t>& output) override;

    /* Start the RTMP handshake procedure. */
    std::vector<uint8_t> StartHandshake(uint32_t timestamp = 0);

    /* Return bytes generated by the handshake and clear the send queue. */
    std::vector<uint8_t> TakeOutboundData();

    ProtocolState state() const { return state_; }
    const char* last_error() const { return last_error_; }


protected:
    void SendSetChunkSize(uint32_t size);

    void SendAcknowledgement(uint32_t sequence);

    void SendWindowAcknowledgementSize(uint32_t size);

    void SendPeerBandwidth(uint32_t size, uint8_t limit_type);

    void SendPingRequest(uint32_t timestamp);

    void SendPingResponse(uint32_t timestamp);

private:
    using NextStep = std::function<bool(std::vector<RtmpMessage>&)>;

    bool HandleC0C1(std::vector<RtmpMessage>& messages);
    bool HandleS0S1S2(std::vector<RtmpMessage>& messages);
    bool HandleC2(std::vector<RtmpMessage>& messages);
    bool HandleRtmp(std::vector<RtmpMessage>& messages);
    void SetRtmpStep();

    /* Mark the protocol as failed with the specified reason. */
    void Fail(const char* reason);
    EndpointRole role_;
    ProtocolState state_ = ProtocolState::kHandshake;
    std::vector<uint8_t> handshake_buffer_;
    std::vector<uint8_t> outbound_data_;
    NextStep next_step_func_;
    RtmpChunkCodec chunk_codec_;
    const char* last_error_ = nullptr;
};

}  // namespace protocol::rtmp
#endif
